### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by finico** [pgb-git/learn-git#5]
- [ ] Коммиты
  - [ ] Правильное именование коммитов
  - [ ] Коммит частичных изменений
- [ ] Фичи/баги
  - [ ] Новая фича/баг
  - [ ] Продолжение фичи/бага вместо другого разработчика
  - [ ] Присоединение к другому разработчику для продолжения с ним фичи/бага
  - [ ] Актуализация ветки относительно базовой (merge/rebase)
  - [ ] Навести порядок в ветке фичи/бага (переименовать/схлопнуть) и убедиться в правильности
  - [ ] Удалить ненужный коммит из ветки фичи/бага
  - [ ] Большая фича (подветки)
- [ ] Релизы
  - [ ] Исправление бага, которое должно попасть в релиз
- [ ] Хотфиксы
  - [ ] Создать хотфикс
  - [ ] Исправление бага, которое должно попасть в хотфикс
- [ ] История
  - [ ] Найти коммиты по определенной задаче
  - [ ] Посмотреть историю определенного файла
  - [ ] Посмотреть, кто изменил определенную строчку в коде
  - [ ] Посмотреть, что изменилось в рамках определенного коммита

**Comment by ndronov** [comment]
Коммит частичных изменений:
git commit -- <имя файла>

**Comment by ndronov** [comment]
Продолжение фичи/бага вместо другого разработчика:
git checkout feature/FN-0_UncompletedFeature
 
**!ВАЖНО:** нельзя схлопывать чужие коммиты со своими

**Comment by ndronov** [comment]
Присоединение к другому разработчику для продолжения с ним фичи/бага:
**!ВАЖНО:**  git pull **--rebase**

**Comment by ndronov** [comment]
Актуализация ветки относительно базовой (merge/rebase):
git fetch origin -p
git rebase origin/develop

**Comment by ndronov** [comment]
Удалить ненужный коммит из ветки фичи/бага

![image](https://cloud.githubusercontent.com/assets/26296037/25276751/da43fa76-26c5-11e7-957d-7923b01d74a9.png)

**Comment by ndronov** [comment]
Примечание:
Для удаления коммита можно заменять pick на **drop**
![image](https://cloud.githubusercontent.com/assets/26296037/25276961/e890b2bc-26c6-11e7-8bb2-6c9cb1c044b0.png)

**Comment by ndronov** [comment]
**Большая фича (подветки)**

**Comment by ndronov** [comment]
###  **Релизы**
Исправление бага, которое должно попасть в релиз

**Comment by ndronov** [comment]
###  Хотфиксы
**Создать хотфикс**

**Comment by ndronov** [comment]
**Исправление бага, которое должно попасть в хотфикс**

**Comment by ndronov** [comment]
### История
**Найти коммиты по определенной задаче**

**Comment by ndronov** [comment]
**Посмотреть историю определенного файла**
git log -p filename
git blame filename

**Comment by ndronov** [comment]
**Посмотреть, кто изменил определенную строчку в коде**
git log -L n,m:filename
git blame filename

**Comment by ndronov** [comment]
**Посмотреть, что изменилось в рамках определенного коммита**
git show commit-hash

**Comment by finico** [comment]
👍
