### ISSUE TITLE
Roadmap Константин

### ISSUE THREAD

**Issue by finico** [pgb-git/learn-git#6]
- [ ] Коммиты
  - [ ] Правильное именование коммитов
  - [ ] Коммит частичных изменений
- [ ] Фичи/баги
  - [ ] Новая фича/баг
  - [ ] Продолжение фичи/бага вместо другого разработчика
  - [ ] Присоединение к другому разработчику для продолжения с ним фичи/бага
  - [ ] Актуализация ветки относительно базовой (merge/rebase)
  - [ ] Навести порядок в ветке фичи/бага (переименовать/схлопнуть) и убедиться в правильности
  - [ ] Удалить ненужный коммит из ветки фичи/бага
  - [ ] Большая фича (подветки)
- [ ] Релизы
  - [ ] Исправление бага, которое должно попасть в релиз
- [ ] Хотфиксы
  - [ ] Создать хотфикс
  - [ ] Исправление бага, которое должно попасть в хотфикс
- [ ] История
  - [ ] Найти коммиты по определенной задаче
  - [ ] Посмотреть историю определенного файла
  - [ ] Посмотреть, кто изменил определенную строчку в коде
  - [ ] Посмотреть, что изменилось в рамках определенного коммита
